### ISSUE TITLE
Error running example.qmd

### ISSUE THREAD

**Issue by gvelasq** [quarto-ext/lightbox#14]
Hello, I am running Quarto version 1.1.251 and installed lightbox into its own RStudio project. Running `example.qmd` yields this error message:

```
Error running filter _extensions/quarto-ext/lightbox/lightbox.lua:
_extensions/quarto-ext/lightbox/lightbox.lua:101: attempt to call a nil value (field 'is_format')
stack traceback:
```

**Comment by dragonstyle** [comment]
Hi - sorry for the issue! This extension now requires the 1.2 version of Quarto, available here:

https://quarto.org/docs/download/prerelease.html

**Comment by gvelasq** [comment]
Thank you! That solves it. Closing this issue.
