### ISSUE TITLE
Figure cross-referencing - unable to resolve crossref @fig

### ISSUE THREAD

**Issue by jav-ed** [quarto-ext/lightbox#19]
Thank you for this very nice extension. Unfortunately, if it is used it removes the figure id, see for example:

`![Data and workflow of the first step: Data generation](../../3_Figs_Pyth/2_Task/1_Data_Gen.svg){#fig-fig_4_Data_Gen}`

Here you see, the figure has the id "fig-fig_4_Data_Gen". When activating lightbox the figure id is removed and the following error occors:

WARNING: Data/1_Writing/2_Task/1_Data_Gen.html: Unable to resolve crossref @fig-fig_4_Data_Gen

Is it possible to have cross-referencing and lightbox working together?

**Comment by dragonstyle** [comment]
Thanks for reporting this - I am looking into it and am seeing the same issue when using Quarto 1.3 (The release candidate). Can you just confirm that you are using Quarto 1.3 (using `quarto --version`) just so I'm sure I'm seeing the same thing you are as I dig into the issue?

**Comment by jav-ed** [comment]
Yes, I updated it recently. Here see my output:
`➜  ~ quarto --version
1.3.321`

Thank you for the fast reply

**Comment by dragonstyle** [comment]
Perfect thank you!

**Comment by cscheid** [comment]
This is a quarto bug! Thanks for the report. We'll fix right away.

**Comment by jav-ed** [comment]
Thank you that solved the issue
