### ISSUE TITLE
Global Install

### ISSUE THREAD

**Issue by matiasandina** [quarto-ext/lightbox#3]
Thank you for giving us this magical extension.
Was wondering whether there's a way to perform a global install, instead of installing in every folder each time we want to use it.

**Comment by dragonstyle** [comment]
Appreciate the kind words! Right now Quarto always requires you to install extensions into individual folders (for documents), or into a project (available for anything in the project). This aides reproducibility as dependencies upon a global store aren't created. Perhaps the project approach could be an improvement for you if you could put the various documents that are using this extension?

**Comment by matiasandina** [comment]
I understand the motivation. Unfortunately, my projects are too unrelated to have them all in one "big project", I guess I will keep installing lightbox whenever needed.

**Comment by dragonstyle** [comment]
Ok, definitely get it. The one other thought that I have (especially if you have a number of extension that you always like to have to available) would be to create a template, which can install extensions and create a starter document using the command:

`quarto use template <github-org>/<github-repo>`

That would at least perhaps simplify the process for you if the template gets more complicated than merely the lightroom extension...
