### ISSUE TITLE
quarto says it can't find the executable

### ISSUE THREAD

**Issue by emilBeBri** [quarto-ext/lightbox#9]
So I get the error:

```
Error running filter lightbox:
Could not find executable lightbox

```

this is clear enough, but I do not get why: from  [GLightbox](https://github.com/biati-digital/glightbox) I installed it with:

```

npm install glightbox

```

Tried searching for lightbox or glightbox with locate on my filesystem, but it does not show up. but it is installed with npm.

This is probably something somewhat obvious, but I don't know what it is. 

I'm on manjaro linux with i3

**Comment by emilBeBri** [comment]
Ok it's because I'm new to quarto and quarto extensions,  this is what I had not understood which is in the documentation:

```
 Rather than installing into a global library, Quarto extensions are installed locally, directly alongside the document or project they are used within. 
```

by cd'ing into my project and running the command, it works perfectly. what a great extension, looks so elegant.

Sorry for taking your time, have a great day!

**Comment by cderv** [comment]
No problem ! Glad it works
